[package]
name = "tij"
version = "0.1.0"
authors = ["Fernando Jascovich <fernando.ej@gmail.com>"]
edition = "2018"

[dependencies]
cursive = "0.16"
reqwest = { version = "0.11.3", features = ["blocking"] }
serde_json = "1.0"

